### PR TITLE
Add Friends Annotations & descrp. stats notebook

### PR DESCRIPTION
**Pull request by complexbrains**
This PR adds Friends Annotations for Seasons 1-8, a jupyer notebook for descriptive statistical properties of transcript details, a csv file of original transcripts for 10 seasons extracted from the original DVDs, a csv file for of internet found transcripts for 10 seasons and a data description json file.

### CODE REVIEW

**Comment by pbellec** [comment]
quick comments:
 * there are functions defined in the notebook, and the notebook is very long. It would be better to create a dedicated module.
 * there are too many depencies, and those are not organize. Many dependencies can likely be pushed in the dedicated module above. It's also good practice to import first very common libraries, then domain specific tools, then niche libraries, and finally custom ones. 
 * notebook is very long and very little text. Add narration and sections. 
 * run a clean execution of the notebook (clear and re-run all cells). I couldn't spot out of order execution issues, but I did spot instances were cells missed numbers (e.g. 103 -> 105).

**Comment by bpinsard** [comment]
quickly noted:
- typo: dataset_descripton.json
- dataset_descripton.json contains int/float as string (with comma for 10^3), should be using numeric types

We should consider putting all these files in annex as they are quite large despite being text and for less obvious exposure of copyrighted materials.

**Comment by complexbrains** [comment]
With this PR I fixed the requested as comments in this [PR](https://github.com/courtois-neuromod/friends.stimuli/pull/2#issuecomment-1741364991)
- A `friends_util.py` module created to curate all the execution of the estimations.
- - Dependencies are cleaned and moved to the `friends_util.py` module. 
- Data is cleaned. 
- Descriptive text is added to the JB. 
- Notebook is shortened.
- Bug in the ngram plots are fixed. 
- Clean run of the notebook is provided.
- `dataset_description.json`is renamed.
- the numerical data in `dataset_description.json` converted from str to int.
- changed the folder naming from `s1` to `s01`
- added .tsv files with word, onset, duration columns for each alignment file. 
- edited the readme

**Comment by complexbrains** [comment]
Closing this PR as I will be pushing htk + assemblyAI annotations together in another PR.

**Pull request closed without merging**
